import { Link } from 'react-router-dom'
import BrandLogo from '../components/BrandLogo'

const SECTIONS = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: [
      {
        type: 'p',
        text: 'These Terms of Service ("Terms") govern your access to and use of InterviewMonitor, including all associated websites, APIs, and services (collectively, the "Service"). By creating an account or using the Service in any capacity, you agree to be bound by these Terms.',
      },
      {
        type: 'p',
        text: 'If you are using the Service on behalf of an organisation, you represent and warrant that you have the authority to bind that organisation to these Terms.',
      },
    ],
  },
  {
    id: 'service-description',
    title: '2. Description of the Service',
    content: [
      {
        type: 'p',
        text: 'InterviewMonitor is a technical interview monitoring platform that allows hiring organisations ("Interviewers") to conduct monitored coding interviews with candidates. The Service provides:',
      },
      {
        type: 'list',
        items: [
          'Creation and management of interview sessions with configurable problem statements and monitoring levels',
          'Generation of one-time invite links sent to candidates',
          'Real-time and recorded screen sharing from the candidate to the interviewer',
          'Behavioural event logging (tab switches, paste events, typing cadence anomalies, etc.)',
          'Risk score calculation based on logged events',
          'Session replay and review tools',
          'Export and reporting capabilities',
        ],
      },
      {
        type: 'p',
        text: 'InterviewMonitor is offered free of charge. There is no paid tier, no trial period, and no credit card required.',
      },
    ],
  },
  {
    id: 'eligibility',
    title: '3. Eligibility',
    content: [
      {
        type: 'p',
        text: 'You must be at least 18 years of age to create an account or conduct interviews using the Service. By using the Service, you represent that you meet this requirement.',
      },
      {
        type: 'p',
        text: 'Candidates invited to interview sessions do not need to create an account but are bound by these Terms and the Privacy Policy when they join a session via an invite link.',
      },
    ],
  },
  {
    id: 'consent-requirement',
    title: '4. Mandatory Candidate Consent',
    content: [
      {
        type: 'p',
        text: 'InterviewMonitor requires explicit, informed candidate consent before any monitoring data is collected. This is a non-negotiable requirement of using the Service.',
      },
      {
        type: 'list',
        items: [
          'Every candidate joining a session is shown a consent screen that discloses exactly what will and will not be monitored during their session.',
          'No session data (events, code snapshots, screen frames, webcam snapshots) is collected before the candidate confirms their consent.',
          'Interviewers must not circumvent, suppress, or misrepresent the consent disclosure to candidates.',
          'Interviewers must not use the Service to monitor individuals who have not been informed that monitoring will take place.',
        ],
      },
      {
        type: 'p',
        text: 'Violation of these consent requirements is grounds for immediate account termination.',
      },
    ],
  },
  {
    id: 'interviewer-responsibilities',
    title: '5. Interviewer Responsibilities',
    content: [
      {
        type: 'p',
        text: 'As an Interviewer using this Service, you agree to:',
      },
      {
        type: 'list',
        items: [
          'Use monitoring data only as one input among many in a holistic human-led evaluation process.',
          'Not use any signal generated by InterviewMonitor as the sole basis for a hiring decision, rejection, or any other consequential outcome for a candidate.',
          'Ensure that your use of the Service complies with all applicable employment and data protection laws in your jurisdiction, including but not limited to the GDPR, CCPA, the Equal Employment Opportunity Act, and applicable state/provincial employment law.',
          'Inform candidates about your organisation\'s data retention policies for interview recordings, if different from InterviewMonitor\'s defaults.',
          'Secure your account credentials and not share them with unauthorised parties.',
          'Not use the Service to conduct interviews in a manner that is discriminatory, harassing, or unlawful.',
          'Delete interview records when they are no longer needed for a lawful purpose.',
        ],
      },
    ],
  },
  {
    id: 'prohibited-uses',
    title: '6. Prohibited Uses',
    content: [
      {
        type: 'p',
        text: 'The following uses of the Service are strictly prohibited:',
      },
      {
        type: 'list',
        items: [
          'Automated hiring decisions — using the risk score or any other data from the Service as the sole or determinative factor in a hiring decision.',
          'Discriminatory use — using monitoring data in a way that discriminates based on race, gender, age, disability, religion, national origin, or any other protected characteristic.',
          'Non-interview monitoring — using the Service to monitor employees, contractors, or individuals outside of an explicit technical interview context.',
          'Circumventing consent — modifying, suppressing, or bypassing the consent screen in any way.',
          'Data scraping or bulk extraction — programmatically extracting data from the Service in bulk without written permission.',
          'Impersonation — creating accounts under false identities or impersonating another person or organisation.',
          'Reverse engineering — attempting to reverse engineer, decompile, or discover the source code of the Service.',
          'Abuse of the free service — creating multiple accounts to bypass any reasonable rate limits or storage limits.',
          'Reselling — selling access to or reselling the Service without written permission.',
        ],
      },
    ],
  },
  {
    id: 'data-ownership',
    title: '7. Data Ownership',
    content: [
      {
        type: 'p',
        text: 'You retain ownership of all data you or your organisation creates within the Service, including interview problem statements, candidate information, and session records.',
      },
      {
        type: 'p',
        text: 'You grant InterviewMonitor a limited, non-exclusive, royalty-free licence to store, process, and transmit your data solely for the purpose of providing the Service to you.',
      },
      {
        type: 'p',
        text: 'We do not use your data to train machine learning models, and we do not share or sell your data with third parties for their own commercial purposes.',
      },
    ],
  },
  {
    id: 'candidate-rights',
    title: '8. Candidate Rights Under These Terms',
    content: [
      {
        type: 'p',
        text: 'Candidates who participate in interviews have the following rights:',
      },
      {
        type: 'list',
        items: [
          'To receive clear, honest disclosure of what is being monitored before joining a session.',
          'To decline participation in a session without penalty from InterviewMonitor (though the interviewing organisation may set its own policies).',
          'To request deletion of all data collected during their session by contacting privacy@interviewmonitor.app.',
          'To request a copy of the data collected about them during any session.',
        ],
      },
    ],
  },
  {
    id: 'service-availability',
    title: '9. Service Availability',
    content: [
      {
        type: 'p',
        text: 'InterviewMonitor is provided on an "as is" and "as available" basis. We do not guarantee that the Service will be available at all times or that it will be free of errors or interruptions.',
      },
      {
        type: 'p',
        text: 'Because the Service is offered free of charge, we do not provide SLA guarantees or uptime commitments. We will make reasonable efforts to maintain availability but reserve the right to perform maintenance, upgrades, or other operations that may temporarily impact availability.',
      },
    ],
  },
  {
    id: 'disclaimers',
    title: '10. Disclaimers and Limitation of Liability',
    content: [
      {
        type: 'p',
        text: 'TO THE FULLEST EXTENT PERMITTED BY LAW, INTERVIEWMONITOR IS PROVIDED WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.',
      },
      {
        type: 'p',
        text: 'IN NO EVENT WILL INTERVIEWMONITOR BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF REVENUE, PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF OR INABILITY TO USE THE SERVICE.',
      },
      {
        type: 'p',
        text: 'BECAUSE THE SERVICE IS FREE, OUR TOTAL LIABILITY TO YOU FOR ANY CLAIM ARISING FROM THESE TERMS OR YOUR USE OF THE SERVICE IS LIMITED TO USD $100.',
      },
    ],
  },
  {
    id: 'indemnification',
    title: '11. Indemnification',
    content: [
      {
        type: 'p',
        text: 'You agree to indemnify, defend, and hold harmless InterviewMonitor and its operators from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising from:',
      },
      {
        type: 'list',
        items: [
          'Your breach of these Terms',
          'Your violation of any applicable law or regulation in connection with your use of the Service',
          'Your use of the Service in a manner that harms a candidate\'s rights or interests',
          'Any claims by your candidates, employees, or third parties related to how you conducted interviews using the Service',
        ],
      },
    ],
  },
  {
    id: 'termination',
    title: '12. Termination',
    content: [
      {
        type: 'p',
        text: 'You may delete your account at any time. Account deletion permanently removes all associated interviews, sessions, events, screen frames, and code snapshots.',
      },
      {
        type: 'p',
        text: 'We reserve the right to suspend or terminate your account, with or without notice, if we determine in our sole discretion that you have violated these Terms or if your use of the Service poses a risk to other users or the integrity of the platform.',
      },
      {
        type: 'p',
        text: 'Upon termination, all licences granted to you under these Terms immediately expire.',
      },
    ],
  },
  {
    id: 'changes',
    title: '13. Changes to These Terms',
    content: [
      {
        type: 'p',
        text: 'We may update these Terms at any time. When we make material changes, we will update the "Last updated" date at the top of this page and notify registered users by email at least 14 days before the changes take effect.',
      },
      {
        type: 'p',
        text: 'Continued use of the Service after the effective date of any changes constitutes your acceptance of the updated Terms.',
      },
    ],
  },
  {
    id: 'governing-law',
    title: '14. Governing Law',
    content: [
      {
        type: 'p',
        text: 'These Terms are governed by and construed in accordance with the laws of the United States. Any disputes arising from these Terms or your use of the Service shall be resolved in the courts of competent jurisdiction in the United States.',
      },
    ],
  },
  {
    id: 'contact',
    title: '15. Contact',
    content: [
      {
        type: 'p',
        text: 'If you have questions about these Terms, please contact us at: legal@interviewmonitor.app',
      },
    ],
  },
]

function Section({ section }) {
  return (
    <div id={section.id} className="space-y-4 scroll-mt-20">
      <h2 className="text-lg font-bold text-white" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
        {section.title}
      </h2>
      {section.content.map((block, i) => {
        if (block.type === 'p') {
          return <p key={i} className="text-sm text-slate-400 leading-relaxed">{block.text}</p>
        }
        if (block.type === 'list') {
          return (
            <ul key={i} className="space-y-2">
              {block.items.map((item, j) => (
                <li key={j} className="flex items-start gap-3 text-sm text-slate-400 leading-relaxed">
                  <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full" style={{ background: '#00ea64' }} />
                  {item}
                </li>
              ))}
            </ul>
          )
        }
        return null
      })}
    </div>
  )
}

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#020617] text-white" style={{ fontFamily: "'IBM Plex Sans', sans-serif" }}>
      {/* Nav */}
      <header className="border-b border-white/[0.06] bg-[#020617]/90 backdrop-blur-xl sticky top-0 z-40">
        <div className="mx-auto flex h-14 max-w-6xl items-center justify-between px-5">
          <Link to="/" className="cursor-pointer">
            <BrandLogo size={26} textSize="text-sm" />
          </Link>
          <div className="flex items-center gap-3">
            <Link to="/login" className="text-xs text-slate-400 hover:text-white transition-colors cursor-pointer">Log in</Link>
            <Link to="/signup"
              className="px-4 py-1.5 rounded-lg text-xs font-semibold text-black cursor-pointer hover:opacity-90 transition-opacity"
              style={{ background: '#00ea64' }}>
              Get started free
            </Link>
          </div>
        </div>
      </header>

      {/* Hero */}
      <div className="border-b border-white/[0.05] py-14 px-5" style={{ background: '#070c18' }}>
        <div className="mx-auto max-w-4xl space-y-3">
          <span className="text-[10px] font-bold tracking-[0.16em] text-[#00ea64] uppercase"
            style={{ fontFamily: "'JetBrains Mono', monospace" }}>Legal</span>
          <h1 className="text-3xl sm:text-4xl font-bold" style={{ fontFamily: "'JetBrains Mono', monospace" }}>
            Terms of Service
          </h1>
          <p className="text-slate-500 text-sm">Last updated: June 22, 2026</p>
        </div>
      </div>

      {/* Layout */}
      <div className="mx-auto max-w-4xl px-5 py-12 lg:grid lg:grid-cols-[220px_1fr] lg:gap-12">
        {/* TOC */}
        <aside className="hidden lg:block">
          <div className="sticky top-20 space-y-1">
            <p className="mb-3 text-[10px] font-bold tracking-[0.12em] text-slate-600 uppercase">Contents</p>
            {SECTIONS.map(s => (
              <a key={s.id} href={`#${s.id}`}
                className="block text-xs text-slate-600 hover:text-slate-300 transition-colors py-0.5 cursor-pointer">
                {s.title}
              </a>
            ))}
          </div>
        </aside>

        {/* Body */}
        <main className="space-y-12 min-w-0">
          <div className="rounded-lg border border-[#00ea64]/15 bg-[#00ea64]/[0.04] px-4 py-3">
            <p className="text-xs text-[#00ea64]/80 leading-relaxed">
              <strong className="text-[#00ea64]">Key points:</strong> The Service is free. Candidate consent is mandatory and non-waivable. Risk scores are signals for human review, not automated decisions. You own your data. We do not sell or share it.
            </p>
          </div>
          {SECTIONS.map(s => <Section key={s.id} section={s} />)}
        </main>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/[0.05] py-6 px-5 text-center">
        <p className="text-xs text-slate-700">
          © {new Date().getFullYear()} InterviewMonitor ·{' '}
          <Link to="/about" className="hover:text-slate-500 transition-colors cursor-pointer">About</Link>
          {' · '}
          <Link to="/privacy" className="hover:text-slate-500 transition-colors cursor-pointer">Privacy Policy</Link>
        </p>
      </footer>
    </div>
  )
}
